baseURL = "https://rymader.github.io/wedding/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
relativeURLs = false
canonifyURLs = true

[params]
  main_page_hero = "photos/main_page_v3.png"
  we_are_getting_married = "photos/we_are_getting_married.png"
  location_banner = "photos/location.png"
  schedule_banner = "photos/schedule.png"
  logo = "photos/logo_v2.png"
  love_journey = "photos/our_love_journey.png"
  love_journey_pt2 = "photos/our_love_journey_pt2.png"
  rsvp = "photos/rsvp.png"
  location_map = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7751.62597932706!2d100.53246907593156!3d13.729769297801445!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x30e29f24163b6223%3A0x1bba6665f2aa49df!2sCrowne%20Plaza%20Bangkok%20Lumpini%20Park%20by%20IHG!5e0!3m2!1sen!2sus!4v1758244461809!5m2!1sen!2sus"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[languages]

  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"
    title = "Ann and Ryan"

    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Home"
        url = "/"
        weight = 1
      [[languages.en.menu.main]]
        name = "RSVP"
        url = "/rsvp/"
        weight = 3
      [[languages.en.menu.main]]
        name = "Details"
        url = "/details/"
        weight = 4
      [[languages.en.menu.main]]
        name = "Our Story"
        url = "/our_story/"
        weight = 5

  [languages.th]
    languageName = "ไทย"
    weight = 2
    contentDir = "content/th"
    title = "แอน และ ไรอัน"

    [languages.th.menu]
      [[languages.th.menu.main]]
        name = "หน้าแรก"
        url = "/"
        weight = 1
      [[languages.th.menu.main]]
        name = "ตอบรับคำเชิญ"
        url = "/rsvp/"
        weight = 3
      [[languages.th.menu.main]]
        name = "รายละเอียด"
        url = "/details/"
        weight = 4
      [[languages.th.menu.main]]
        name = "เรื่องราวของเรา"
        url = "/our_story/"
        weight = 5
